# AirSim settings
airsim:
   host: "127.0.0.1"
   port: 41451
   timeout: 60
   headless: true

unreal:
   project_path: "IstanbulWaste/IstanbulWaste.uproject"
   editor_path: "/opt/UnrealEngine/Engine/Binaries/Linux/UnrealEditor"
   maps:
      - name: "BosphorusWaterfront"
        description: "Beşiktaş-Ortaköy style waterfront"
        proportion: 0.25
      - name: "NarrowStreets"
        description: "Balat/Karaköy narrow streets"
        proportion: 0.25
      - name: "YildizPark"
        description: "Yıldız Park area"
        proportion: 0.25
      - name: "ModernPlaza"
        description: "Modern urban plaza"
        proportion: 0.25

image_generation:
   total_images: 10000
   resolution:
      width: 1280
      height: 720
   formats:
      - rgb
      - depth
      - segmentation

waste:
   models:
      - name: "PlasticBottle"
        scale_range: [0.8, 1.2]
        rotation_range: [0, 360]
        proportion: 0.20
      - name: "SodaCan"
        scale_range: [0.8, 1.2]
        rotation_range: [0, 360]
        proportion: 0.15
      - name: "PlasticBag"
        scale_range: [0.8, 1.5]
        rotation_range: [0, 360]
        proportion: 0.15
      - name: "FaceMask"
        scale_range: [0.8, 1.2]
        rotation_range: [0, 360]
        proportion: 0.10
      - name: "CardboardBox"
        scale_range: [0.8, 1.5]
        rotation_range: [0, 360]
        proportion: 0.10
      - name: "CoffeeCup"
        scale_range: [0.8, 1.2]
        rotation_range: [0, 360]
        proportion: 0.10
      - name: "CigaretteButt"
        scale_range: [0.8, 1.2]
        rotation_range: [0, 360]
        proportion: 0.10
      - name: "FoodContainer"
        scale_range: [0.8, 1.5]
        rotation_range: [0, 360]
        proportion: 0.10
   density:
      min: 1
      max: 15
   clustering:
      enabled: true
      probability: 0.6
      cluster_size_range: [2, 5]
      cluster_radius_range: [0.5, 2.0]

drone:
   altitude_range: [3.0, 15.0]
   tilt_angle_range: [0, 30]
   movement:
      min_speed: 0.0
      max_speed: 2.0
      trajectory_types: ["hover", "linear", "arc", "zigzag"]

lighting:
   conditions:
      - name: "Sunny"
        proportion: 0.4
        intensity_range: [0.8, 1.0]
        shadow_strength_range: [0.6, 0.9]
      - name: "Overcast"
        proportion: 0.3
        intensity_range: [0.5, 0.7]
        shadow_strength_range: [0.2, 0.4]
      - name: "Dawn"
        proportion: 0.15
        intensity_range: [0.4, 0.6]
        shadow_strength_range: [0.3, 0.7]
        color_temperature_range: [3000, 4000]
      - name: "Dusk"
        proportion: 0.15
        intensity_range: [0.3, 0.5]
        shadow_strength_range: [0.4, 0.8]
        color_temperature_range: [2000, 3000]

rendering:
   batch_size: 100
   num_workers: 8
   output_dir: "dataset"
   label_format: "yolo"

seed: 42
logging:
   level: "INFO"
   file: "logs/simulation.log"
